log:
  level: "info"
limit: 1000
webApiEndpoint: "https://webapi.default-tenant.app.dev73.lab.iguazeng.com"
container: "bigdata"
username: "iguazio"
password: "t0ps3cr3t"

backends:
- type: "kv"
- type: "stream"
- type: "tsdb"
  workers: 16
- type: "csv"
  rootdir: "/mnt/csvroot"
